### ISSUE TITLE
Rust 1.78 breaks filebuffer for empty files

### ISSUE THREAD

**Issue by jfcg** [ruud-v-a/filebuffer#9]
With Rust `1.78`, when trying to open an empty file with:
```rust
use filebuffer::FileBuffer;

fn main() {
    let fbuf = FileBuffer::open("emptyFile").expect("failed to open file");
    println!("Size {}", fbuf.len());
}
```
I get
```
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
```
When there is some content in the file, it runs fine.

`filebuffer` needs to use `NonNull::dangling()` instead of `null` when necessary, and switch to `.length == 0` instead of `.buffer == null` check.

**Comment by jfcg** [comment]
It can also implement `len()` by just returning `.length`

**Comment by jfcg** [comment]
Btw, `null` value is a long established empty/invalid pointer value in many languages and operating systems.
Why is Rust trying to invent & push a new convention like `NonNull::dangling()` ? Does not make sense to me.
For example this broke `filebuffer` for no pragmatic reason.

**Comment by ruuda** [comment]
Thanks for bringing this to my attention! The fix for this was simple enough, return `&[]` if the buffer pointer is null instead of using `slice::from_raw_parts`. As to why the pointer needs to be non-null, I suppose it is needed for some internal invariants.

The `len()` method is already provided by the `Deref<Target = [u8]>`, I would assume LLVM is able to optimize out the indirection, though I haven’t verified this.

I’ve published a new release to crates.io that is compatible with Rust 1.78.

**Comment by jfcg** [comment]
thanks..
